# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13419ce5335967303fb8b4b14de9b911"
name = "return-monitor"
handle = "return-monitor-1"
application_url = "https://varieties-non-breath-growing.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "app-tutorial-test.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://varieties-non-breath-growing.trycloudflare.com/auth/callback",
  "https://varieties-non-breath-growing.trycloudflare.com/auth/shopify/callback",
  "https://varieties-non-breath-growing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
