# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bdbe89ca7aa014d20b8f64bd7e6d3226"
name = "return-monitor"
handle = "return-monitor"
application_url = "https://organisation-organic-sc-contribution.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-5663cd0a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_returns"

[auth]
redirect_urls = [
  "https://organisation-organic-sc-contribution.trycloudflare.com/auth/callback",
  "https://organisation-organic-sc-contribution.trycloudflare.com/auth/shopify/callback",
  "https://organisation-organic-sc-contribution.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
